name: Build

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      releaseVersion:
        type: string
        required: false
        default: ''
  push:
    branches:
      - 'main'
      - 'release/*'
  pull_request:
    branches:
      - 'main'
      - 'release/*'

jobs:
  build:
    name: Build maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Set up Java ENV
        uses: actions/setup-java@v4
        with: # The last version will be used by default and available globally via JAVA_HOME.
          java-version: |
            17
            8
          distribution: 'temurin'
          cache: maven

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Prepare version
        if: ${{ inputs.releaseVersion != '' }}
        run: 'mvn versions:set -DnewVersion=${{ inputs.releaseVersion }}'

      - name: Build and Test with Maven
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_8_X64 }}
        run: mvn clean install

      - name: Save Package / Artifact
        if: ${{ inputs.releaseVersion != '' }}
        uses: actions/upload-artifact@v3
        with:
          name: 'saas-aem-${{ inputs.releaseVersion }}'
          path: all/target/*.zip

      - name: Analyze with SonarQube
        if: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
        run: mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=valtech-ch_saas-aem-module
